### ISSUE TITLE
mysql_conn.erl line102, not a good variable name？

### ISSUE THREAD

**Issue by mingchaoyan** [fredrikt/yxa#9]
```
ConnPid = self(),
Pid = spawn(fun () ->
        init(Host, Port, User, Password, Database, LogFun, ConnPid)
    end),
```

ConnPid is not a good name. It may make people confused with real erlang-mysql-driver connect pid. Eg, If people start mysql:start_link/6 in erlang shell, self() will get the mysql_dispacher's pid.

**Comment by fredrikt** [comment]
It is a variable only used internally in the start/6 function, so it does not appear that important to me to change it.

If you want to provide a fix (read: pull request) I'll accept it if it looks good, but I will close this issue as "won't fix".
